@startuml
class com.klbc.app.dao.OrderDaoImpl {
+ void order(Order,Map<Integer,Integer>,Integer)
+ List<Order> findDetails(Integer)
+ List<OrderDetail> findByOrderId(Integer)
+ Order findById(int)
+ void pay(Order)
+ void deleteOrder(Order)
}
class com.klbc.app.service.OrderServiceImpl {
- OrderDaoImpl orderDao
+ void order(Map<Integer,Integer>,String,Integer)
+ List<Order> findDetails(Integer)
+ Order findById(int)
+ void pay(Order)
+ void deleteOrder(Order)
}
class com.klbc.app.dao.Basedao {
- {static} String driver
- {static} String url
- {static} String username
- {static} String password
+ {static} Connection getConnection()
+ {static} ResultSet execute(PreparedStatement,Connection,String,Object[],ResultSet)
+ {static} int update(PreparedStatement,Connection,String,Object[])
+ {static} boolean closeResource(PreparedStatement,Connection,ResultSet)
}
interface com.klbc.app.dao.FoodDao {
~ List<Food> findByFoodTypeId(Integer)
~ Food findByFoodId(Integer)
~ int getFoodCount(int)
}
interface com.klbc.app.service.OrderService {
~ void order(Map<Integer,Integer>,String,Integer)
~ List<Order> findDetails(Integer)
~ Order findById(int)
~ void pay(Order)
~ void deleteOrder(Order)
}
class com.klbc.app.servlet.commentServlet {
- {static} long serialVersionUID
# void service(HttpServletRequest,HttpServletResponse)
}
class com.klbc.app.service.UserServiceImpl {
~ UserDaoImpl userDao
+ User findByLoginNameAndPass(String,String)
}
interface com.klbc.app.dao.OrderDao {
~ void order(Order,Map<Integer,Integer>,Integer)
~ List<Order> findDetails(Integer)
~ List<OrderDetail> findByOrderId(Integer)
~ Order findById(int)
~ void pay(Order)
~ void deleteOrder(Order)
}
class com.klbc.app.pojo.Comment {
- Integer id
- Integer userId
- Integer foodId
- String content
- Integer disabled
- Date createTime
- User user
+ Integer getId()
+ void setId(Integer)
+ Integer getNameId()
+ void setNameId(Integer)
+ Integer getFoodId()
+ void setFoodId(Integer)
+ String getContent()
+ void setContent(String)
+ Integer getDisabled()
+ void setDisabled(Integer)
+ Date getCreateTime()
+ void setCreateTime(Date)
+ String toString()
+ User getUser()
+ void setUser(User)
}
class com.klbc.app.pojo.PageBean {
- List<E> list
- Integer currPage
- Integer pageSize
- Integer totalPage
- Integer totalCount
+ List<E> getList()
+ void setList(List<E>)
+ Integer getCurrPage()
+ void setCurrPage(Integer)
+ Integer getPageSize()
+ void setPageSize(Integer)
+ Integer getTotalPage()
+ Integer getTotalCount()
+ void setTotalCount(Integer)
}
class com.klbc.app.pojo.Feedback {
}
interface com.klbc.app.dao.FoodTypeDao {
~ List<FoodType> findAll()
}
class com.klbc.app.dao.FoodTypeDaoImpl {
+ List<FoodType> findAll()
}
class com.klbc.app.pojo.User {
- int id
- String userCode
- String userName
- String userPassword
- Integer gender
- Date birthday
- String phone
- String address
- Integer userRole
- int createdBy
- Date creationDate
- int modifyBy
- Date modifyDate
- Integer age
- String userRoleName
+ String getUserRoleName()
+ void setUserRoleName(String)
+ Integer getAge()
+ int getId()
+ void setId(int)
+ String getUserCode()
+ void setUserCode(String)
+ String getUserName()
+ void setUserName(String)
+ String getUserPassword()
+ void setUserPassword(String)
+ Integer getGender()
+ void setGender(Integer)
+ Date getBirthday()
+ void setBirthday(Date)
+ String getPhone()
+ void setPhone(String)
+ String getAddress()
+ void setAddress(String)
+ Integer getUserRole()
+ void setUserRole(Integer)
+ int getCreatedBy()
+ void setCreatedBy(int)
+ Date getCreationDate()
+ void setCreationDate(Date)
+ int getModifyBy()
+ void setModifyBy(int)
+ Date getModifyDate()
+ void setModifyDate(Date)
}
class com.klbc.app.dao.FoodDaoImpl {
+ List<Food> findByFoodTypeId(Integer)
+ Food findByFoodId(Integer)
+ int getFoodCount(int)
}
interface com.klbc.app.service.FoodService {
~ List<Food> findByFoodTypeId(Integer)
~ Food findByFoodId(Integer)
~ int getFoodCount(int)
}
class com.klbc.app.servlet.loginServlet {
- {static} long serialVersionUID
# void service(HttpServletRequest,HttpServletResponse)
}
class com.klbc.app.servlet.indexServlet {
- {static} long serialVersionUID
# void service(HttpServletRequest,HttpServletResponse)
}
class com.klbc.app.service.CommentServiceImpl {
~ CommentDaoImpl commentDao
+ List<Comment> findByFoodId(int)
+ void comment(int,int,String)
}
interface com.klbc.app.dao.CommentDao {
~ List<Comment> findByFoodId(int)
~ void comment(int,int,String)
}
class com.klbc.app.service.FoodTypeServiceImpl {
- FoodTypeDaoImpl foodTypeDao
+ List<FoodType> findAll()
}
class com.klbc.app.pojo.FoodType {
- int id
- String typeName
- int createdBy
- Date creationDate
- int modifyBy
- Date modifyDate
- Integer disabled
+ int getId()
+ void setId(int)
+ String getTypeName()
+ void setTypeName(String)
+ int getCreatedBy()
+ void setCreatedBy(int)
+ Date getCreationDate()
+ void setCreationDate(Date)
+ int getModifyBy()
+ void setModifyBy(int)
+ Date getModifyDate()
+ void setModifyDate(Date)
+ Integer getDisabled()
+ void setDisabled(Integer)
+ String toString()
}
class com.klbc.app.dao.JDBCDao {
+ {static} void insertOrDeleteOrUpdate(String)
+ {static} List<Map<String,Object>> select(String)
+ {static} List<Map<String,Object>> returnResultToList(ResultSet)
}
class com.klbc.app.servlet.orderServlet {
- {static} long serialVersionUID
# void service(HttpServletRequest,HttpServletResponse)
}
interface com.klbc.app.service.UserService {
~ User findByLoginNameAndPass(String,String)
}
class com.klbc.app.servlet.LoginOutServlet {
- {static} long serialVersionUID
# void service(HttpServletRequest,HttpServletResponse)
}
interface com.klbc.app.service.CommentService {
~ List<Comment> findByFoodId(int)
~ void comment(int,int,String)
}
interface com.klbc.app.service.FoodTypeService {
~ List<FoodType> findAll()
}
class com.klbc.app.dao.CommentDaoImpl {
+ List<Comment> findByFoodId(int)
+ void comment(int,int,String)
}
class com.klbc.app.pojo.Food {
- int id
- String foodName
- int foodTypeId
- double price
- String remark
- String img
- int createdBy
- Date creationDate
- int modifyBy
- Date modifyDate
- Integer disabled
- FoodType foodType
- Integer buyNum
+ int getId()
+ void setId(int)
+ String getFoodName()
+ void setFoodName(String)
+ int getFoodTypeId()
+ void setFoodTypeId(int)
+ double getPrice()
+ void setPrice(double)
+ String getRemark()
+ void setRemark(String)
+ String getImg()
+ void setImg(String)
+ int getCreatedBy()
+ void setCreatedBy(int)
+ Date getCreationDate()
+ void setCreationDate(Date)
+ int getModifyBy()
+ void setModifyBy(int)
+ Date getModifyDate()
+ void setModifyDate(Date)
+ Integer getDisabled()
+ void setDisabled(Integer)
+ FoodType getFoodType()
+ void setFoodType(FoodType)
+ Integer getBuyNum()
+ void setBuyNum(Integer)
+ String toString()
}
class com.klbc.app.pojo.Order {
- Integer id
- String orderCode
- Double totalPrice
- Integer status
- Date orderTime
- Date payTime
- Date updateTime
- Integer disabled
- Integer userId
- List<OrderDetail> orderDetail
+ Integer getId()
+ void setId(Integer)
+ String getOrderCode()
+ void setOrderCode(String)
+ Double getTotalPrice()
+ void setTotalPrice(Double)
+ Integer getStatus()
+ void setStatus(Integer)
+ Date getOrderTime()
+ void setOrderTime(Date)
+ Date getPayTime()
+ void setPayTime(Date)
+ Date getUpdateTime()
+ void setUpdateTime(Date)
+ Integer getDisabled()
+ void setDisabled(Integer)
+ List<OrderDetail> getOrderDetail()
+ void setOrderDetail(List<OrderDetail>)
+ String toString()
+ Integer getUserId()
+ void setUserId(Integer)
}
interface com.klbc.app.dao.UserDao {
+ User getLoginUser(Connection,String)
+ int updatePwd(Connection,int,String)
+ int getUserCount(Connection,String,int)
+ List<User> getUserList(Connection,String,int,int,int)
+ int addUser(Connection,User)
+ int deleteUserById(Connection,Integer)
+ int modify(Connection,User)
+ User getUserById(Connection,String)
~ User findByLoginNameAndPass(String,String)
}
class com.klbc.app.servlet.ShopCarServlet {
- {static} long serialVersionUID
# void service(HttpServletRequest,HttpServletResponse)
}
class com.klbc.app.service.FoodServiceImpl {
- FoodDaoImpl FoodDao
+ List<Food> findByFoodTypeId(Integer)
+ Food findByFoodId(Integer)
+ int getFoodCount(int)
}
class com.klbc.app.pojo.OrderDetail {
- Integer id
- Integer orderId
- Integer foodId
- Integer buyNum
- Integer disabled
- Food food
+ Integer getId()
+ void setId(Integer)
+ Integer getOrderId()
+ void setOrderId(Integer)
+ Integer getFoodId()
+ void setFoodId(Integer)
+ Integer getBuyNum()
+ void setBuyNum(Integer)
+ Integer getDisabled()
+ void setDisabled(Integer)
+ Food getFood()
+ void setFood(Food)
+ String toString()
}
class com.klbc.app.dao.UserDaoImpl {
+ User findByLoginNameAndPass(String,String)
+ User getLoginUser(Connection,String)
+ int updatePwd(Connection,int,String)
+ int getUserCount(Connection,String,int)
+ List<User> getUserList(Connection,String,int,int,int)
+ int addUser(Connection,User)
+ int deleteUserById(Connection,Integer)
+ int modify(Connection,User)
+ User getUserById(Connection,String)
}


com.klbc.app.dao.OrderDao <|.. com.klbc.app.dao.OrderDaoImpl
com.klbc.app.service.OrderService <|.. com.klbc.app.service.OrderServiceImpl
javax.servlet.http.HttpServlet <|-- com.klbc.app.servlet.commentServlet
com.klbc.app.service.UserService <|.. com.klbc.app.service.UserServiceImpl
java.io.Serializable <|.. com.klbc.app.pojo.PageBean
com.klbc.app.dao.FoodTypeDao <|.. com.klbc.app.dao.FoodTypeDaoImpl
com.klbc.app.dao.FoodDao <|.. com.klbc.app.dao.FoodDaoImpl
javax.servlet.http.HttpServlet <|-- com.klbc.app.servlet.loginServlet
javax.servlet.http.HttpServlet <|-- com.klbc.app.servlet.indexServlet
com.klbc.app.service.CommentService <|.. com.klbc.app.service.CommentServiceImpl
com.klbc.app.service.FoodTypeService <|.. com.klbc.app.service.FoodTypeServiceImpl
javax.servlet.http.HttpServlet <|-- com.klbc.app.servlet.orderServlet
javax.servlet.http.HttpServlet <|-- com.klbc.app.servlet.LoginOutServlet
com.klbc.app.dao.CommentDao <|.. com.klbc.app.dao.CommentDaoImpl
javax.servlet.http.HttpServlet <|-- com.klbc.app.servlet.ShopCarServlet
com.klbc.app.service.FoodService <|.. com.klbc.app.service.FoodServiceImpl
com.klbc.app.dao.UserDao <|.. com.klbc.app.dao.UserDaoImpl
@enduml